version: "3.9"  # optional since v1.27.0
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: orangetv
      MYSQL_PASSWORD: pass
      MYSQL_USER: user

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

  kafka:
    image: ubuntu/kafka
    environment:
      TZ: Asia/Shanghai
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9095
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://127.0.0.1:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    entrypoint: sh -c 'exec kafka-server-start.sh /etc/kafka/server.properties
      --override listeners=$$KAFKA_LISTENERS
      --override advertised.listeners=$$KAFKA_ADVERTISED_LISTENERS
      --override listener.security.protocol.map=$$KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      --override inter.broker.listener.name=$$KAFKA_INTER_BROKER_LISTENER_NAME
      --override zookeeper.connect=$$KAFKA_ZOOKEEPER_CONNECT'
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - 9095:9095

  video-repo:
    image: nginx
    hostname: orangetv-cloud-web
    volumes:
      - /d/Video/videocache:/usr/share/nginx/html:ro
      - ./nginx-template:/etc/nginx/templates:ro
    environment:
      - OUTER_HOSTNAME=$USERDOMAIN
    ports:
      - 9090:80

  zookeeper:
    image: ubuntu/zookeeper
    environment:
      TZ: Asia/Shanghai
