package com.orangetv.cloud.videostore.model;

import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   Video metadata extracted from FS.
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table video
 */
public class Video {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.id")
    private Integer id;

    /**
     * Database Column Remarks:
     *   视频名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.name")
    private String name;

    /**
     * Database Column Remarks:
     *   存储路径
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.path")
    private String path;

    /**
     * Database Column Remarks:
     *   封面ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.cover")
    private String cover;

    /**
     * Database Column Remarks:
     *   播放时长
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.length")
    private Long length;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.name")
    public String getName() {
        return name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.name")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.path")
    public String getPath() {
        return path;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.path")
    public void setPath(String path) {
        this.path = path;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.cover")
    public String getCover() {
        return cover;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.cover")
    public void setCover(String cover) {
        this.cover = cover;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.length")
    public Long getLength() {
        return length;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: video.length")
    public void setLength(Long length) {
        this.length = length;
    }
}