server:
  port: 9300

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}

spring:
  application:
    name: @name@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orangetv
    username: user
    password: pass
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9500
  kafka:
    bootstrap-servers: host.docker.internal:9095
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
  sql:
    init:
      username: root
      password: example
      schema-locations: classpath:schema-mysql.sql
      mode: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    #    org.springframework.boot.autoconfigure:
    com.orangetv.cloud.videostore.mapper: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info

orangetv:
  video-scan-path: ${SCAN_PATH:D:\Video\videocache}
  video-scan-suffixes: .mp4,.MP4
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
