server:
  port: 9500
  servlet:
    session:
      cookie:
        name: AUTH-SERVER

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

spring:
  application:
    name: @name@

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure:

management:
  endpoints:
    web:
      exposure:
        include: health,info
