server:
  port: 9300

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}

spring:
  application:
    name: @name@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orangetv
    username: user
    password: pass

management:
  endpoints:
    web:
      exposure:
        include: health,info
