server:
  port: 9000

# 允许使用lb开头的uri
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: strip-api
          uri: lb://GATEWAY
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
      actuator:
        verbose:
          enabled: false
  application:
    name: @name@
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${OUTER_HOST:localhost}:9500
      client:
        registration:
          orangetv-cloud-server-gateway:
            provider: spring
            client-name: Orange Cloud TV
            client-id: orangetv-cloud-server-gateway
            client-secret: orangetv-cloud-server-gateway
            authorization-grant-type: authorization_code
            redirect-uri: "http://${OUTER_HOST:127.0.0.1}:\
              ${OUTER_PORT:8080}/login/oauth2/code/{registrationId}"
            scope: openid,video.metadata.read,album.metadata.read
        provider:
          spring:
            issuer-uri: http://${OUTER_HOST:localhost}:9500

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure:

# gateway会自动注册服务到eureka
eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

orangetv:
  enable-location-rewrite: true
